"""

Revision ID: 2eab31837d70
Revises: da008f819148
Create Date: 2026-03-11 19:51:47.913451
"""

from collections.abc import Sequence

from alembic import op

revision: str = "2eab31837d70"
down_revision: str | None = "da008f819148"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_bookmarks_favorite"), "bookmarks", ["favorite"], unique=False
    )
    op.create_index(op.f("ix_bookmarks_title"), "bookmarks", ["title"], unique=False)
    op.drop_constraint(op.f("tags_name_key"), "tags", type_="unique")
    op.create_index(op.f("ix_tags_name"), "tags", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tags_name"), table_name="tags")
    op.create_unique_constraint(
        op.f("tags_name_key"), "tags", ["name"], postgresql_nulls_not_distinct=False
    )
    op.drop_index(op.f("ix_bookmarks_title"), table_name="bookmarks")
    op.drop_index(op.f("ix_bookmarks_favorite"), table_name="bookmarks")
    # ### end Alembic commands ###
