"""

Revision ID: 3939181ce2ab
Revises: 9bee72dc2f41
Create Date: 2026-03-10 20:05:43.272560
"""

from collections.abc import Sequence

revision: str = "3939181ce2ab"
down_revision: str | None = "9bee72dc2f41"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
