"""added users table

Revision ID: 440a4e87bc2c
Revises: 9688bc18499b
Create Date: 2026-03-15 14:15:28.186296
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "440a4e87bc2c"
down_revision: str | None = "9688bc18499b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.add_column("bookmarks", sa.Column("user_id", sa.Uuid(), nullable=False))
    op.drop_constraint(op.f("bookmarks_url_key"), "bookmarks", type_="unique")
    op.create_unique_constraint(None, "bookmarks", ["user_id", "url"])
    op.create_foreign_key(
        None, "bookmarks", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("tags", sa.Column("user_id", sa.Uuid(), nullable=False))
    op.drop_index(op.f("ix_tags_name"), table_name="tags")
    op.create_index(op.f("ix_tags_name"), "tags", ["name"], unique=False)
    op.create_unique_constraint(None, "tags", ["user_id", "name"])
    op.create_foreign_key(
        None, "tags", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tags", type_="foreignkey")
    op.drop_constraint(None, "tags", type_="unique")
    op.drop_index(op.f("ix_tags_name"), table_name="tags")
    op.create_index(op.f("ix_tags_name"), "tags", ["name"], unique=True)
    op.drop_column("tags", "user_id")
    op.drop_constraint(None, "bookmarks", type_="foreignkey")
    op.drop_constraint(None, "bookmarks", type_="unique")
    op.create_unique_constraint(
        op.f("bookmarks_url_key"),
        "bookmarks",
        ["url"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("bookmarks", "user_id")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
