"""

Revision ID: 4eaa3cabd98c
Revises: a80365c9a354
Create Date: 2026-03-15 17:00:31.196867
"""

from collections.abc import Sequence

revision: str = "4eaa3cabd98c"
down_revision: str | None = "a80365c9a354"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
