"""

Revision ID: 9688bc18499b
Revises: 2eab31837d70
Create Date: 2026-03-12 20:56:21.360054
"""

from collections.abc import Sequence

revision: str = "9688bc18499b"
down_revision: str | None = "2eab31837d70"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
