"""Improved favorite default

Revision ID: 9bee72dc2f41
Revises: a9735e4f26e2
Create Date: 2026-03-09 21:24:20.929362
"""

from collections.abc import Sequence

revision: str = "9bee72dc2f41"
down_revision: str | None = "a9735e4f26e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
