"""

Revision ID: da008f819148
Revises: 3939181ce2ab
Create Date: 2026-03-10 20:15:22.990446
"""

from collections.abc import Sequence

revision: str = "da008f819148"
down_revision: str | None = "3939181ce2ab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
